Section "Device"
  Identifier "DummyDevice"
  Driver "dummy"
  VideoRam 256000
EndSection

Section "Monitor"
  Identifier "DummyMonitor"
  HorizSync 28-80
  VertRefresh 48-75
  Modeline "2560x1600_60.00"  348.50  2560 2752 3032 3504  1600 1603 1609 1658 -hsync +vsync
EndSection

Section "Screen"
  Identifier "DummyScreen"
  Device "DummyDevice"
  Monitor "DummyMonitor"
  DefaultDepth 24
  SubSection "Display"
    Depth 24
    Modes "2560x1600"
  EndSubSection
EndSection